### ISSUE TITLE
Design doc for first (only playable?) floor of hotel

### ISSUE THREAD

**Issue by dantogno** [dantogno/fancy-footwork#32]
@katkeller, now that we have this can you add it to the wiki? Might be we need it in a way to update the text easily online. But don't sink too much time into that if it's a pain.

**Comment by katkeller** [comment]
It's now in there with the changes you requested! I'll work on making it easy to change the text online.

https://github.com/dantogno/fancy-footwork/wiki/Gameplay-Layout-%231
