### ISSUE TITLE
Find reference art for old film cameras with winding

### ISSUE THREAD

**Issue by dantogno** [dantogno/fancy-footwork#5]

**Comment by katkeller** [comment]
![older-black-film-photo-camera-with-flash-unit-attached-on-top-isolated-against-pure-white-RMKY7K (1)](https://user-images.githubusercontent.com/43050286/59297129-1be6ed00-8c4d-11e9-9a3c-4640a1212780.jpg)
Back:
![Canon_AE-1_back](https://user-images.githubusercontent.com/43050286/59297135-1ee1dd80-8c4d-11e9-8adf-3e39fef8c75a.jpg)
For the flash shape/size:
![d-rendering-retro-vintage-camera-flash-top-isolate-white-background-clipping-paths-easy-to-split-out-97607385](https://user-images.githubusercontent.com/43050286/59297139-20130a80-8c4d-11e9-963c-1dc9e2db86c2.jpg)
